### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by AprendendoRapido** [alyleite/bbbot#1]

**Comment by alyleite** [comment]
Qual Windows você está utilizando?

Já tentou colocar o caminho do python no path?

Vá em Painel de Controle -> Sistema e Segurança -> Sistema -> Configurações avançadas do sistema.
1. Clique em Variáveis de ambiente
2. Edite a variável 'PATH'
3. Adicione 2 novos caminhos 'C:\Python27' e 'C:\Python27\scripts' (Altere 'C:\Python27' pelo caminho onde instalou o python) e salve
Execute o cmd novamente e digite python para ver se funcionou.
Caso sim, teste novamente o app
