### ISSUE TITLE
Muitas imagens (maioria duplicada)

### ISSUE THREAD

**Issue by robson9954** [alyleite/bbbot#26]
Tem mais de 3 mil imagens, tá deixando a comparação de imagens pesada e lenta. Foi feita a correção mas as antigas ainda ficaram.

**Comment by robson9954** [comment]
Poderíamos até apagar imagens mais antigas, já que a cada novo evento as imagens do BD atualiza. Preserva somente algumas do último evento.

**Comment by alyleite** [comment]
Não cheguei a ver se as imagens antigas ainda são exibidas. 
Caso não, é possível apagá-las então

**Comment by alyleite** [comment]
Estou verificando aqui e algumas realmente estão duplicadas, porém tem bastante imagem.
Vou apagando aos poucos quando tiver tempo.
Se puder ajudar, agradeço.
