### ISSUE TITLE
Local onde é salvo imagem

### ISSUE THREAD

**Issue by matheusmhpc** [alyleite/bbbot#4]
Acredito que a imagem deveria ser salva em images_tmp e só serem movidas para images (para validar a certa) se o retorno da resposta for simbolo errado...

Uma dúvida que eu tenho é: caso o bot escolha uma imagem random (se ele não conhecer) e acerte ele salva lá na pasta de imagens individuais?

**Comment by alyleite** [comment]
> Acredito que a imagem deveria ser salva em images_tmp e só serem movidas para images (para validar a certa) se o retorno da resposta for simbolo errado

Bem colocado. No momento não está fazendo isso.



> Uma dúvida que eu tenho é: caso o bot escolha uma imagem random (se ele não conhecer) e acerte ele salva lá na pasta de imagens individuais?

Não salva no momento.

Se quiser colaborar fica a vontade.
Vlew

**Comment by matheusmhpc** [comment]
Fiz no código e subirei em breve pra pasta só estou tentando resolver um bug que ele não tá detectando quando dá erro no captcha... fechando issue.
