### ISSUE TITLE
Erro ao adicionar imagens

### ISSUE THREAD

**Issue by robson9954** [alyleite/bbbot#5]
Quando adiciono imagens em 'src/images_individual' dá o seguinte erro:

Download captcha from URL: Cadeira
Traceback (most recent call last):
  File "./src/compare_images.py", line 52, in <module>
    for name, image in list_individual_images(PATH_EXISTENT):
  File "C:\Users\user\Desktop\bbbot-master\src\utils.py", line 20, in list_individual_images
    image = Image.open(filename)
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file './src/images_individual/Thumbs.db'

**Comment by alyleite** [comment]
Opa, chegou a executar o install.bat?
Caso sim, tenta executar esse na mão:
pip install -r requirements.txt

Rodei aqui normal e foi.
Qual a versão do python instalada?

**Comment by robson9954** [comment]
Pois é, tive que baixar novamente o repositório e executar tudo novamente. Deu certo.

**Comment by alyleite** [comment]
blz, qualquer coisa abre outra issue vlew
