### ISSUE TITLE
Bbbot trava depois de um tempo

### ISSUE THREAD

**Issue by robson9954** [alyleite/bbbot#7]
Depois de um tempo (às vezes até mesmo na primeira tentativa) o script para. Aí tenho que realizar alguma ação (clicar na imagem, recarregar captcha) para ele continuar tentando, depois para novamente. Trava exatamente em "Get captcha' e não realiza mais nenhum ação:

Logged in.
Download captcha from URL: Mesa
Get captcha: Mesa | Position: 1
Download captcha from URL: moto
Get captcha: moto | Position: 4
Votos computados: 1
Download captcha from URL: janela
Get captcha: janela | Position: 4
Download captcha from URL: pocao
Get captcha: pocao | Position: 2
Download captcha from URL: planeta
Captcha Response: Símbolo errado, tente de novo
Get captcha: planeta | Position: 4
Download captcha from URL: cartao
Captcha Response: Símbolo errado, tente de novo
Get captcha: cartao | Position: 1
Download captcha from URL: planeta
Captcha Response: Símbolo errado, tente de novo
Votos computados: 2
Get captcha: planeta | Position: 1
Download captcha from URL: moto
Get captcha: moto | Position: 0
Download captcha from URL: dado
Get captcha: dado | Position: 0
Votos computados: 3
Download captcha from URL: caixa
Get captcha: caixa | Position: 0

Rodei manual 'pip install -r requirements.txt', atualizei o 'puppeteer' para ultima versão e nada.

**Comment by robson9954** [comment]
Python versão 3.7

**Comment by alyleite** [comment]
Ele fica com essa imagem?

![image](https://user-images.githubusercontent.com/7413346/78509427-39e58700-7764-11ea-8079-31f343069b32.png)

Se sim, é a globo que trava o votos. Sempre espero um tempo para continuar.

**Comment by robson9954** [comment]
Não. Ele simplesmente trava. Depois de computar e votar novamente ele para, normalmente. Mas o site tá apresentando muita instabilidade, ai fica difícil também.

**Comment by robson9954** [comment]
Fica assim:

![image](https://user-images.githubusercontent.com/20285781/78513336-2b599880-7781-11ea-9605-a37320e3727e.png)

Só volta quando vou manualmente errar ou acertar o captcha

**Comment by alyleite** [comment]
vou fazer uns testes, mas ainda não consegui reproduzir

**Comment by matheusmhpc** [comment]
@alyleite como eu consigo falar contigo? vou tentar implementar algumas coisas mas queria entender o fluxo... tu tem telegram?

**Comment by robson9954** [comment]
Parece que resolveu aqui. Testei aqui e ainda não parou. A qualquer momento mando mais imagens. Fechando aqui a issue.
